version: '3.8'

services:
  # Nginx static file server
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VERSION=1.0.0
    image: hub.qpaas.com/aimod/llm-streaming-api:latest
    container_name: llm-streaming-nginx
    restart: unless-stopped
    ports:
      - "80:8080"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--spider", "http://localhost:8080/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3 