version: '3.8'

services:
  # Go API service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llm-streaming-api
    restart: unless-stopped
    environment:
      - PORT=8080
      - STATIC_DIR=./llm-streaming-tester
    ports:
      - "80:8080"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--spider", "http://localhost:8080/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3 