version: '3.8'

services:
  # Go API service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llm-streaming-api
    restart: unless-stopped
    environment:
      - PORT=8080
      - STATIC_DIR=./llm-streaming-tester
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--spider", "http://localhost:8080/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Nginx service
  nginx:
    image: nginx:alpine
    container_name: llm-streaming-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--spider", "http://localhost/health"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  app-network:
    driver: bridge 